### ISSUE TITLE
antimev: 4 nodes crash with error "panic: failed to retrieve next block validators: failed to perform 'getCurrentConsensus' call: execution aborted (timeout = 5s)"

### ISSUE THREAD

**Issue by songb2** [bane-labs/go-ethereum#356]
#### System information

Version: 0.3.0-unstable
Git Commit: 20d7ab409f31bd36bf8e73014f90107ca2c43965
Git Commit Date: 20241203
Architecture: amd64
Go Version: go1.22.2
Operating System: linux
GOPATH=
GOROOT=

#### Expected behaviour
Should work without panic error

#### Actual behaviour
4 nodes crash and stop working with error 

#### Steps to reproduce the behaviour
The issue is related to this in development PR https://github.com/bane-labs/go-ethereum/pull/332
1. start seven privnet with cmd
`make privnet_start_seven`
2. start a new node in CN mode, and then voted it to be the new CN (the step maybe optinal)
3. Keep the privnet work running one night

#### Backtrace
```
node1
...
2024-12-04T01:06:16.566+0800	DEBUG	dbft@v0.3.1-0.20241128121733-94bc38235e44/check.go:111	not enough to commit	{"count": 4}
2024-12-04T01:06:16.566+0800	DEBUG	dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:231	received message	{"type": "Commit", "from": 0, "height": 3044, "view": 0, "my_height": 3044, "my_view": 0}
2024-12-04T01:06:16.738+0800	DEBUG	dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:231	received message	{"type": "Commit", "from": 3, "height": 3044, "view": 0, "my_height": 3044, "my_view": 0}
2024-12-04T01:06:16.778+0800	INFO	dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:588	received Commit	{"validator": 3}
2024-12-04T01:06:16.805+0800	INFO	dbft@v0.3.1-0.20241128121733-94bc38235e44/check.go:120	approving block	{"height": 3044, "hash": "0xd679ef4ba453aa0323d6b101e27799523fda67c6fa51dfe8be58b2e46c7615c8", "tx_count": 0, "merkle": "0xf8c71ec88104109d3af57cfdaac1a33ffacd3a7e5ba9e92fb0d7f9620f921527", "prev": "0xc42c5c2a31a57c42932e62a3873e4d52fa37155a572442ea6d7764ba5fe638cd"}
INFO [12-04|01:06:17.456] Chain reorg detected                     number=3042 hash=0a6d8d..e912cf drop=1 dropfrom=cadf91..7e5a02 add=2 addfrom=385596..c36a9b
INFO [12-04|01:06:21.950] Successfully wrote new block with state  number=3044 hash=385596..c36a9b
INFO [12-04|01:06:22.874] New block in the chain                   "dbft index"=3044 "chain index"=3044 hash=0x38559698d9bd5597c9493f449d04d766d2f56d599aa5ba879844a65d46c36a9b "parent hash"=0xc42c5c2a31a57c42932e62a3873e4d52fa37155a572442ea6d7764ba5fe638cd primary=6 coinbase=0x1212000000000000000000000000000000000003 "mix digest"=0x808e594003e9050fb7225a9d410a3bb3249e67f5a25c8f8e620eab217c600494
ERROR[12-04|01:06:36.701] handleDKG error                          height=3044 err="failed to call epochDuration: failed to call at state 'epochDuration': execution aborted (timeout = 5s)"
INFO [12-04|01:06:38.290] Fetching latest sealing proposal         "desired number"=3045
INFO [12-04|01:07:32.683] Commit new sealing work                  number=3045 sealhash=58ffa8..2993e1 "parent hash"=385596..c36a9b etherbase=0x1212000000000000000000000000000000000003 txs=0  gas=0          fees=0          elapsed=1m9.900s
INFO [12-04|01:07:33.368] Sealing proposal updated                 number=3045 sealhash=58ffa8..2993e1 "parent hash"=385596..c36a9b txs=0
panic: failed to retrieve next block validators: failed to perform 'getCurrentConsensus' call: execution aborted (timeout = 5s)

goroutine 4519 [running]:
github.com/ethereum/go-ethereum/consensus/dbft.New.func4({0x0, 0x66d7049d443f49c9?, 0x87baa59a596df5d2?})
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:373 +0x216
github.com/nspcc-dev/dbft.(*Context[...]).reset(0x1fcfd00, 0x0, 0x34a9e590ab2dc901)
	github.com/nspcc-dev/dbft@v0.3.1-0.20241128121733-94bc38235e44/context.go:243 +0xdc
github.com/nspcc-dev/dbft.(*DBFT[...]).initializeConsensus(0x1fd3460, 0x0, 0x4)
	github.com/nspcc-dev/dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:93 +0x45
github.com/nspcc-dev/dbft.(*DBFT[...]).Reset(...)
	github.com/nspcc-dev/dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:89
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).handleChainBlock(0xc0003186c8, 0xc0082fd408, 0x38?)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1977 +0xa96
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).eventLoop(0xc0003186c8)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1790 +0xbc5
created by github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).Start in goroutine 4535
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1572 +0x476


node2

INFO [12-04|01:06:27.476] Looking for peers                        peercount=8 tried=0 static=0
ERROR[12-04|01:06:30.434] handleDKG error                          height=3044 err="failed to call epochDuration: failed to call at state 'epochDuration': execution aborted (timeout = 5s)"
INFO [12-04|01:06:31.914] Fetching latest sealing proposal         "desired number"=3045
...

2024-12-04T10:12:07.630+0800	DEBUG	dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:231	received message	{"type": "RecoveryRequest", "from": 6, "height": 4933, "view": 0, "my_height": 4933, "my_view": 0}


node3
...
ERROR[12-04|01:06:34.049] handleDKG error                          height=3044 err="failed to call epochDuration: failed to call at state 'epochDuration': execution aborted (timeout = 5s)"
...
2024-12-04T10:12:07.606+0800	DEBUG	dbft@v0.3.1-0.20241128121733-94bc38235e44/send.go:8	broadcasting message	{"type": "RecoveryRequest", "height": 4933, "view": 0}




node4
...
ERROR[12-04|01:06:51.784] handleDKG error                          height=3044 err="failed to call epochDuration: failed to call at state 'epochDuration': execution aborted (timeout = 5s)"
...
INFO [12-04|10:10:25.789] Sealing proposal updated                 number=4933 sealhash=6786e6..4e1ebd "parent hash"=e5ed01..472e4d txs=3
panic: failed to retrieve next block validators: failed to perform 'getCurrentConsensus' call: execution aborted (timeout = 5s)

goroutine 4460 [running]:
github.com/ethereum/go-ethereum/consensus/dbft.New.func4({0x0, 0x162730dba9a51547?, 0xc3c6663f0e3f5581?})
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:373 +0x216
github.com/nspcc-dev/dbft.(*Context[...]).reset(0x1fcfd00, 0x0, 0xc23687306e572714)
	github.com/nspcc-dev/dbft@v0.3.1-0.20241128121733-94bc38235e44/context.go:243 +0xdc
github.com/nspcc-dev/dbft.(*DBFT[...]).initializeConsensus(0x1fd3460, 0x0, 0x4d2e47d3187b757a)
	github.com/nspcc-dev/dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:93 +0x45
github.com/nspcc-dev/dbft.(*DBFT[...]).Reset(...)
	github.com/nspcc-dev/dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:89
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).handleChainBlock(0xc00057ad88, 0xc007650f08, 0x38?)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1977 +0xa96
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).eventLoop(0xc00057ad88)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1790 +0xbc5
created by github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).Start in goroutine 4520
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1572 +0x476


node5
...
ERROR[12-04|01:06:33.675] handleDKG error                          height=3044 err="failed to call epochDuration: failed to call at state 'epochDuration': execution aborted (timeout = 5s)"
...
panic: failed to retrieve next block validators: failed to perform 'getCurrentConsensus' call: execution aborted (timeout = 5s)

goroutine 4549 [running]:
github.com/ethereum/go-ethereum/consensus/dbft.New.func4({0x0, 0x7b59be38c3289c3b?, 0x545ee630e07377e1?})
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:373 +0x216
github.com/nspcc-dev/dbft.(*Context[...]).reset(0x1fcfd00, 0x0, 0x2da7d6033ed11e18)
	github.com/nspcc-dev/dbft@v0.3.1-0.20241128121733-94bc38235e44/context.go:243 +0xdc
github.com/nspcc-dev/dbft.(*DBFT[...]).initializeConsensus(0x1fd3460, 0x0, 0xe736857a46d7f27a)
	github.com/nspcc-dev/dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:93 +0x45
github.com/nspcc-dev/dbft.(*DBFT[...]).Reset(...)
	github.com/nspcc-dev/dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:89
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).handleChainBlock(0xc00023e6c8, 0xc00e62ef08, 0x38?)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1977 +0xa96
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).eventLoop(0xc00023e6c8)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1790 +0xbc5
created by github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).Start in goroutine 4497
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1572 +0x476



node6

...
INFO [12-04|10:10:20.028] Sealing proposal updated                 number=4933 sealhash=f453f2..ac4c06 "parent hash"=e62d07..8536e7 txs=3
panic: failed to retrieve next block validators: failed to perform 'getCurrentConsensus' call: execution aborted (timeout = 5s)

goroutine 4536 [running]:
github.com/ethereum/go-ethereum/consensus/dbft.New.func4({0x0, 0x7b59be38c3289c3b?, 0x545ee630e07377e1?})
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:373 +0x216
github.com/nspcc-dev/dbft.(*Context[...]).reset(0x1fcfd00, 0x0, 0x6a27bf58848c18bb)
	github.com/nspcc-dev/dbft@v0.3.1-0.20241128121733-94bc38235e44/context.go:243 +0xdc
github.com/nspcc-dev/dbft.(*DBFT[...]).initializeConsensus(0x1fd3460, 0x0, 0xe736857a46d7f27a)
	github.com/nspcc-dev/dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:93 +0x45
github.com/nspcc-dev/dbft.(*DBFT[...]).Reset(...)
	github.com/nspcc-dev/dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:89
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).handleChainBlock(0xc000556b48, 0xc00cbb8788, 0x38?)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1977 +0xa96
github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).eventLoop(0xc000556b48)
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1790 +0xbc5
created by github.com/ethereum/go-ethereum/consensus/dbft.(*DBFT).Start in goroutine 4502
	github.com/ethereum/go-ethereum/consensus/dbft/dbft.go:1572 +0x476


node7

...
2024-12-04T10:12:07.647+0800	DEBUG	dbft@v0.3.1-0.20241128121733-94bc38235e44/dbft.go:231	received message	{"type": "RecoveryRequest", "from": 6, "height": 4933, "view": 0, "my_height": 4933, "my_view": 0}



node9

...
ERROR[12-04|01:07:32.454] handleDKG error                          height=3044 err="failed to call sharePeriodDuration: failed to call at state 'sharePeriodDuration': execution aborted (timeout = 5s)"
...
2024-12-04T10:12:07.651+0800	DEBUG	dbft@v0.3.1-0.20241128121733-94bc38235e44/send.go:8	broadcasting message	{"type": "RecoveryMessage", "height": 4933, "view": 0}
```
@txhsl @chenquanyu

**Comment by txhsl** [comment]
So the panic is from the following codes. As you can see, the reason is a timeout in EVM, which means the contract calling was not able to get executed in 5 seconds.

https://github.com/bane-labs/go-ethereum/blob/14c45aa203b23b8584420f2c961be53dc031e982/internal/ethapi/api.go#L1163-L1184

@songb2 I prefer to say it was because of a lack of performance, as we have already known in practice. But the logic may should be improved to ensure the system contract execution? @AnnaShaleva

**Comment by AnnaShaleva** [comment]
Yes, and it's a very good catch, we have to rework this logic because system calls must not be restricted by 5 seconds. For example, from `getValidators` call depends the whole consensus logic, so the node should take as much time as needed to perform this call. The same statement is relevant for all system contract calls made by dBFT module.
